### ISSUE TITLE
Having Problem while installing a npm package

### ISSUE THREAD

**Issue by yonu676** [notN1CHO/Discord-OGP#2]
![image](https://user-images.githubusercontent.com/72970437/230744179-3e264545-fd2f-4fbc-b806-70838b27085a.png)

**Comment by notN1CHO** [comment]
Hey, you should type this command to install pm2
`sudo npm install -g pm2`

**Comment by yonu676** [comment]
> Hey, you should type this command to install pm2 `sudo npm install -g pm2`

![image](https://user-images.githubusercontent.com/72970437/230744387-72151dcf-09ba-4246-a8c3-02d650060137.png)
i upgraded nodejs version to 18.15.0 and its giving me this err message

**Comment by notN1CHO** [comment]
so as i can see there is a problem between nodejs version and pm2 package, i advice you to downgrade nodejs to v12

**Comment by notN1CHO** [comment]
then try to install pm2 
and change start command in package.json from `"start": "node index.js"` to `"start": "npx node index.js"`

**Comment by yonu676** [comment]
> sudo npm install -g pm2

thanks, its working now
