### ISSUE TITLE
problem creating

### ISSUE THREAD

**Issue by lemhllwess** [notN1CHO/Discord-OGP#4]
when i need to create a game thos bot say error buy the login is true all is fine . 
![image](https://github.com/notN1CHO/Discord-OGP/assets/144817718/31488174-fa23-47b7-97d6-d9d9bfead565)
![issue](https://github.com/notN1CHO/Discord-OGP/assets/144817718/b184a4ee-c4da-4b19-ab6c-ca251c5b39bd)

**Comment by notN1CHO** [comment]
Change your Remote server id to your remote ID, you may find it in settings of your OGP (default: 1)

**Comment by notN1CHO** [comment]
Any other problem feel free to contact me.
